name: PBIT
favicon: null
layout_spectrum: 0.7426999846938998
typography_spectrum: 0.399910545675084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6226189867593348
  lightness: 0.9611588960979134
  saturation: 0.2880568145774305
  rhythmicContrast: 0.904682302614674
purpose: []
