name: PBIT
favicon: null
layout_spectrum: 0.51348
typography_spectrum: 0.88273
title: Performance-Based Interval Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3e3e'
    - '#ffffff'
    - '#9e9e9e'
    - '#c2c2c2'
    - '#787878'
  brandStrength: 0.625
  lightness: 0.9611588960979134
  saturation: 0.2880568145774305
  rhythmicContrast: 0.904682302614674
purpose: []
